---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver_config:
      platform: centos
      image: centos:centos6
  - name: ubuntu-14.04
    driver_config:
      platform: ubuntu
      image: ubuntu:14.04
  - name: ubuntu-12.04
    driver_config:
      platform: ubuntu
      image: ubuntu:12.04

suites:
  - name: default
    run_list:
      - recipe[localedef::default]
    attributes:
